apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-cleaner-controller 
  namespace: monitor 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-cleaner-controller
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-cleaner-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: gpu-cleaner-controller
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  namespace: monitor
  name: gpu-cleaner-controller
