apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-cleaner-controller 
  namespace: gpu-cleaner-controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-cleaner-controller
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "patch"] # Add delete if everything else works
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"] # Add delete if everything else works
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"] # Add delete if everything else works

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-cleaner-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: gpu-cleaner-controller
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  namespace: gpu-cleaner-controller
  name: gpu-cleaner-controller
